### PR TITLE
Add extra cookies option on every request

### PR DESCRIPTION
**Pull request by brunowonka**
While I'm here, also add the GerritAccount cookie on every request type instead of only GET.

### CODE REVIEW

**Comment by brunowonka** [comment]
I seem to need some special cookies on the Gerrit instance I work with, and I'd love to be able to use this plugin, this seems to work. Full disclosure: I've never written any typescript so I'm sorry in advance if some of this is entirely out of style.

**Comment by SanderRonde** [comment]
Hmm I'm wondering which extra cookies you need for it to work. Could it be that my implementation just didn't work? (possibly because cookies were only applied to GET requests)

If not I'll definitely consider this PR. You missed a few spots where `new GerritAPI` is called but apart from that it's all good :)

**Comment by brunowonka** [comment]
I honestly can't tell if the GerritAccount cookie works or not; the instance I'm working against wants some very specific single-sign-on cookies and it seems to ignore `GerritAccount` entirely.

**Comment by SanderRonde** [comment]
Ah okay, did you test whether it works with your changes? I'll fix up the last few call sites of `GerritAPI` real quick

**Comment by brunowonka** [comment]
Yeah I'm currently running a locally built version of the plugin. Works great.

One thing I just noticed is that the version on `package.json` at `:main` is `1.2.17` but the version on the marketplace seems to be `1.2.18`

**Comment by SanderRonde** [comment]
Ah good one, looks like I didn't push my changes. Will merge this and release as `1.2.19`, thanks for the PR!

**Comment by SanderRonde** [comment]
Done!

**Pull request merged**
